[stylance]
# Output file for generated CSS
output_file = "target/site/stylance.css"

# Folders to watch for CSS modules
folders = ["web/src"]

# File extensions to process
extensions = [".module.css", ".module.scss"]

# Class name format (can be short for development, long for production)
class_name_pattern = "[local]_[hash:base64:8]"

# Enable CSS minification
minify = false

# Enable source maps
source_maps = true